### ISSUE TITLE
Support for EAR extensions

### ISSUE THREAD

**Issue by fitzthum** [veraison/rust-ear#14]
It seems like EAR allows the token to be extended with additional fields, but this crate does not seem to support this. Are there any plans to add support for extensions.

I'm not sure this crate will work for us without extensions. See https://github.com/confidential-containers/trustee/issues/353

**Comment by thomas-fossati** [comment]
Hi @fitzthum, apologies for the delayed response - summer vacations and maintaining low-latency communication don't exactly go hand in hand.

First of all, thank you for bringing up the issue, which we confirm is genuine (@setrofim  has already started looking into how to address it.)

Second, it may make sense (or not, I'll let you decide) to document Trustee's extensions in the [EAR document](https://github.com/thomas-fossati/draft-ear) the same way we do with [Veraison's](https://www.ietf.org/archive/id/draft-fv-rats-ear-03.html#name-project-veraison-extensions).  If you want to do so, I'd be happy to help with that.

**Comment by fitzthum** [comment]
> Second, it may make sense (or not, I'll let you decide) to document Trustee's extensions in the [EAR document](https://github.com/thomas-fossati/draft-ear) the same way we do with [Veraison's](https://www.ietf.org/archive/id/draft-fv-rats-ear-03.html#name-project-veraison-extensions). If you want to do so, I'd be happy to help with that.

I think it probably makes sense to document the extensions at some point, but we'll need some time to figure out exactly what we want to include in the token.

**Comment by setrofim** [comment]
@fitzthum  support for extensions has been added with https://github.com/veraison/rust-ear/commit/2eaaead0aed57c2ee88b95e549358738d0da3ba1. Please let us know if that resolves this issue.

**Comment by fitzthum** [comment]
Thanks @setrofim. The changes look great, although I haven't yet tried to use them.
