### ISSUE TITLE
Add function to get names of all supported TrustClaims

### ISSUE THREAD

**Issue by fitzthum** [veraison/rust-ear#18]
It's a little awkward to work with the trust claim names. It would be handy if the crate had an interface to list all of the supported trust claims. This allows the consumer of the crate to iterate through the claims without having to keep their own list, which could get out of sync. 

Also, it seems like it might be good to track these with an enum. You can use `strum` to convert that into strings and back.

**Comment by setrofim** [comment]
You can access supported trust claims by iterating over a trust vector. The claim's name is accessible via `tag()` method. To get the list of supported claims you can do:

```rust
 let claims_names: Vec<String> = Appraisal::new().trust_vector.into_iter().map(|c| c.tag().to_string()).collect();
```
