### ISSUE TITLE
Specifying verification key trustworthy for JSON serialization

### ISSUE THREAD

**Issue by Xynnn007** [veraison/rust-ear#23]
Due to spec https://www.ietf.org/archive/id/draft-ietf-rats-eat-31.html#section-9.6, an EAT'd better have some way to specify the trustworthy of the verification key. For now the APIs to serialize EAR to JWT is
- [sign_jwt_pem](https://docs.rs/ear/0.2.0/ear/struct.Ear.html#method.sign_jwt_pem)(&self, alg: [Algorithm](https://docs.rs/ear/0.2.0/ear/enum.Algorithm.html), key: &[[u8](https://doc.rust-lang.org/nightly/std/primitive.u8.html)])
- [sign_jwk_der](https://docs.rs/ear/0.2.0/ear/struct.Ear.html#method.sign_jwk_der)(&self, alg: [Algorithm](https://docs.rs/ear/0.2.0/ear/enum.Algorithm.html), key: &[[u8](https://doc.rust-lang.org/nightly/std/primitive.u8.html)])

I propose to add two more
- `sign_jwt_pem/der_with_kid(&self, alg: Algorithm, key: &[u8], kid: &str)`: This will do same thing with `sign_jwt_pem/der`, but also it will fill the JWT's `kid` header item, which will be used by the verifiers to look up their configured key store.
- `sign_jwt_pem/der_with_jwk(&self, alg: Algorithm, key: &[u8], jwk: &[u8],x5c: Option<&str>)`: This will do same thing with `sign_jwt_pem/der` with `key`. The `jwk` will be filled into the JWT's `jwk` header and `x5c` be filled into `x5c` extension if any. The two are used by the verifiers to verify the signature. `x5c` together with the TrustRoot configured on the user side would be used to verify the trustworthy of the jwk.

**Comment by setrofim** [comment]
I've added `_with_header` version of the methods that take a `jwt::Header` as an argument. This removes the need to define different methods for each header/combination of header that might need to be added.

Please see https://github.com/veraison/rust-ear/pull/29

**Comment by setrofim** [comment]
Resolved by https://github.com/veraison/rust-ear/pull/29
