### ISSUE TITLE
v0.3.0 release

### ISSUE THREAD

**Issue by fitzthum** [veraison/rust-ear#28]
Thanks to @setrofim I think we don't have any more immediate blockers to using this crate with Trustee. Thanks for the work. Is there any plan to cut a release with thee new features?

**Comment by setrofim** [comment]
There is still an outstanding pull. Once that's resolved, I should be able to create the next release. I'll try to get it published by the end of the week.

**Comment by setrofim** [comment]
Release published: 

https://github.com/veraison/rust-ear/releases/tag/v0.3.0
https://crates.io/crates/ear/0.3.0
